---
parameters:
  - name: rootModuleFolderRelativePath
    default: '.'
  - name: terraformCliVersion
    default: 'latest'
  - name: serviceConnectionNameTfPlan
    type: string
    default: 'sc-alz-mgmt-plan'
  - name: backendStateVariableGroup
    type: string
    default: 'alz-mgmt'
  - name: terraformOverrideVars
    type: object
    default: {}
  - name: terraformWorkspace
    type: string
    default: 'dev'
  - name: moduleAliases
    type: object
    default: []

variables:
  - group: ${{ parameters.backendStateVariableGroup }}
  - name: 'selfHostedAgent'
    value: 'true'

stages:
  - stage: validate
    displayName: Validation Terraform
    jobs:
      - job: validate
        displayName: Validate Terraform
        pool:
          name: alz-mgmt
        steps:
          - template: helpers/terraform-installer.yaml
            parameters:
              terraformVersion: ${{ parameters.terraformCliVersion }}
          - pwsh: |
              terraform `
              -chdir="${{ parameters.rootModuleFolderRelativePath }}" `
              fmt `
              -check
            displayName: Terraform Format Check
          - pwsh: |
              terraform `
              -chdir="${{ parameters.rootModuleFolderRelativePath }}" `
              init `
              -backend=false
            displayName: Terraform Init
          - pwsh: |
              terraform `
              -chdir="${{ parameters.rootModuleFolderRelativePath }}" `
              validate
            displayName: Terraform Validate
      - deployment: plan
        dependsOn: validate
        displayName: Validate Terraform Plan
        pool:
          name: alz-mgmt
        environment: alz-mgmt-plan
        timeoutInMinutes: 0
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout Terraform Module
                  persistCredentials: true
                  path: src
                - ${{ each mod in parameters.moduleAliases }}:
                  - checkout: ${{ mod.alias }}
                    path: src/modules/${{ mod.alias }}
                
                - pwsh: |
                    Write-Host "Listing $(Pipeline.Workspace)/src"
                    if (Test-Path "$(Pipeline.Workspace)/src") {
                      Get-ChildItem -Path "$(Pipeline.Workspace)/src" -Recurse -Force | ForEach-Object { Write-Output $_.FullName }
                    } else {
                      Write-Host "Directory not found: $(Pipeline.Workspace)/src"
                    }
                  displayName: List src folder contents
                  
                - template: helpers/terraform-installer.yaml
                  parameters:
                    terraformVersion: ${{ parameters.terraformCliVersion }}
                - template: helpers/terraform-init.yaml
                  parameters:
                    serviceConnection: ${{ parameters.serviceConnectionNameTfPlan }}
                    backendAzureResourceGroupName: $(BACKEND_AZURE_RESOURCE_GROUP_NAME)
                    backendAzureStorageAccountName: $(BACKEND_AZURE_STORAGE_ACCOUNT_NAME)
                    backendAzureStorageAccountContainerName: $(BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME)
                    backendAzureStorageAccountContainerKeyName: "${{ parameters.terraformWorkspace }}/terraform.tfstate"
                    rootModuleFolderRelativePath: ${{ parameters.rootModuleFolderRelativePath }}
                - template: helpers/terraform-workspace.yaml
                  parameters:
                    serviceConnection: ${{ parameters.serviceConnectionNameTfPlan }}
                    terraformWorkspace: ${{ parameters.terraformWorkspace }}
                - template: helpers/terraform-plan.yaml
                  parameters:
                    serviceConnection: ${{ parameters.serviceConnectionNameTfPlan }}
                    rootModuleFolderRelativePath: ${{ parameters.rootModuleFolderRelativePath }}
